### ISSUE TITLE
update shanbay sync method

### ISSUE THREAD

**Issue by mengziin** [yihong0618/2023#2]
hello yihong:
Thx for your repository , with your [2022](https://github.com/yihong0618/2022/issues/new) I commence  recording my digital memories in my repository. 

I use shanbay to recite English words everyday . with your "daily" package I found the shanbay.py codes. But now in the year of 2023 ,your shanbay API url "https://apiv3.shanbay.com/uc/checkin/calendar/dates/?user_id=..." has already lost effectiveness . 

I traced the shanbay official web and found an new url "https://apiv3.shanbay.com/uc/checkin/logs?user_id=...&ipp=10&page=1" can replace the old url's function . But we should update some code with the new url's response.

In my mind I can fix the shanbay codes , do you mind I pull an request to your repository?

your friend, yumeng.

**Comment by yihong0618** [comment]
@mengziin also shanbay codes in GitHubPoster~
